version: '3.4'
services:
  php:
    build:
      context: ./
    container_name: php
    depends_on:
      - mysql
    volumes:
      - 'app_code:/app'
  nginx:
    build: ./docker/nginx
    container_name: nginx
    depends_on:
      - php
    volumes:
      - 'app_code:/app'
    ports:
      - '80:80'
  mysql:
    build: ./docker/mysql
    container_name: mysql
    volumes:
      - 'app_code:/app'
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    command: mysqld --sql-mode=""
volumes:
  app_code:
    name: 'app_code_volume'